# DSC540-T302 Data Preparation Term Project  
## Milestone 3 : Cleaning/Formatting Website Data

In [130]:
import pandas as pd
from bs4 import BeautifulSoup

# Open the website and read as HTML
with open("GDP by Country _ MacroTrends.html", "r", encoding="utf-8") as fd:
    Soup = BeautifulSoup(fd, "html.parser")

print(Soup.prettify())

<!DOCTYPE html>
<!-- saved from url=(0087)https://www.macrotrends.net/global-metrics/countries/ranking/gdp-gross-domestic-product -->
<html class="js flexbox canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths" style="">
 <!--<![endif]-->
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <link href="https://www.macrotrends.net/global-metrics/countries/ranking/gdp-gross-domestic-product" rel="canonical"/>
  <title>
   GDP by Country | MacroTrends
  </title>
  <meta content="" name="description"/>
  <meta content="" name="robots"/>
  <link href="https://www.macrotrends.net/assets/images/icons/FAVICON/macrotrends-favicon.ico" rel="icon" type="image/x-icon"/>
  <meta content="1228954C688F5907894001CD8E5E624B" name="msvalidate.01"/>
  <meta content="6MnD_3iDtAP1ZyoGK1YMyVIVck4r5Ws80I9xD3ue4_A" name="google-site-verification"/>
  <!-- Load in Roboto Font -->
  <link href="./GDP by Country _ MacroTrends_files/css" rel="stylesheet"/>
  <!-- Bootstrap -->
  <link href="./GDP by Country _ MacroTrends_files/bootstrap.min.css" rel="stylesheet"/>
  <!--for Bootstrap CDN version-->
  <link href="./GDP by Country _ MacroTrends_files/bootstrap-theme.min.css" rel="stylesheet"/>
  <!-- Font Awesome -->
  <link href="./GDP by Country _ MacroTrends_files/font-awesome.min.css" rel="stylesheet"/>
  <!--for Font Awesome CDN version-->
  <!-- Jquery, Bootstrap and Menu Javascript -->
  <script crossorigin="anonymous" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" src="./GDP by Country _ MacroTrends_files/jquery-1.12.4.min.js.download">
  </script>
  <script src="./GDP by Country _ MacroTrends_files/bootstrap.min.js.download">
  </script>
  <script language="javascript" src="./GDP by Country _ MacroTrends_files/jquery.iframetracker.js.download" type="text/javascript">
  </script>
  <!-- Sticky kit for sticky sidebar ad -->
  <script language="javascript" src="./GDP by Country _ MacroTrends_files/jquery.sticky-kit.min.js.download" type="text/javascript">
  </script>
  <!-- Modernizr for cross-browser support -->
  <script src="./GDP by Country _ MacroTrends_files/modernizr-2.6.2-respond-1.1.0.min.js.download" type="text/javascript">
  </script>
  <!-- Latest compiled and minified CSS -->
  <link href="./GDP by Country _ MacroTrends_files/fuelux.min.css" rel="stylesheet"/>
  <!-- Latest compiled and minified JavaScript -->
  <script src="./GDP by Country _ MacroTrends_files/fuelux.min.js.download">
  </script>
  <!-- Twitter Card data -->
  <meta content="summary_large_image" name="twitter:card"/>
  <meta content="@tmacrotrends" name="twitter:site"/>
  <meta content="GDP by Country" name="twitter:title"/>
  <meta content="" name="twitter:description"/>
  <!-- Open Graph data -->
  <meta content="" property="og:url"/>
  <meta content="GDP by Country" property="og:title"/>
  <meta content="" property="og:description"/>
  <!-- JQXGRID STYLES AND JAVASCRIPT -->
  <link href="./GDP by Country _ MacroTrends_files/jqx.base.css" rel="stylesheet" type="text/css"/>
  <link href="./GDP by Country _ MacroTrends_files/jqx.bootstrap.css" rel="stylesheet" type="text/css"/>
  <!-- LOAD THESE SCRIPTS EARLY SO THE TICKER INPUT FIELD IS STYLED INSTANTLY -->
  <script src="./GDP by Country _ MacroTrends_files/jqxcore.js.download" type="text/javascript">
  </script>
  <script src="./GDP by Country _ MacroTrends_files/jqxdata.js.download" type="text/javascript">
  </script>
  <script src="./GDP by Country _ MacroTrends_files/jqxinput.js.download" type="text/javascript">
  </script>
  <!-- Styling for search box -->
  <link href="./GDP by Country _ MacroTrends_files/jquery.typeahead_pages.css" rel="stylesheet" type="text/css"/>
  <!-- Search box javascript -->
  <script src="./GDP by Country _ MacroTrends_files/jquery.typeahead.min.js.download">
  </script>
  <link href="./GDP by Country _ MacroTrends_files/select2.min.css" rel="stylesheet"/>
  <script src="./GDP by Country _ MacroTrends_files/select2.min.js.download">
  </script>
  <!-- ToolTips -->
  <script src="./GDP by Country _ MacroTrends_files/tipped.js.download">
  </script>
  <link href="./GDP by Country _ MacroTrends_files/tipped.css" rel="stylesheet"/>
  <!-- Google tag (gtag.js) -->
  <script async="" src="./GDP by Country _ MacroTrends_files/js">
  </script>
  <script>
   window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());

		  gtag('config', 'G-3KL0LYERBH');
  </script>
  <!-- Load in Macrotrends style sheet -->
  <link href="./GDP by Country _ MacroTrends_files/macrotrends_main.css" rel="stylesheet"/>
  <!--for Font Awesome CDN version-->
  <style>
   .header_content_container {

	width:100%;
	background-color:#444;
	padding: 0px;
}

.header_container {

	min-width:1248px;
	max-width:1248px;
	height:50px;
	padding:15px 0px 10px -20px;
	margin: 0 auto;
	background-color:#444;

}


.header_logo {

	padding-top:10px;
	margin-left:20px;

}


.menu_parent_container {

	width:100%;
	height:34px;
	font-size:16px;
	padding:15px 0px 10px -20px;
	margin:0px 0px 0px 0px;
	background-color:#0089de;
}

.menu_container {

	width:1248px;
	height:34px;
	font-size:16px;
	padding:11px 0px 0px -20px;
	margin: 0 auto;
	background-color:#0089de;
	z-index:1000;
}

.main_content_container {

	min-width: 1248px;
	max-width: 1248px;
	padding: 0px 30px 100px 30px;

}
  </style>
  <script async="" src="./GDP by Country _ MacroTrends_files/js(1)" type="text/javascript">
  </script>
 </head>
 <body class="fuelux" cz-shortcut-listen="true">
  <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
  <div class="header_content_container container-fluid">
   <div class="header_parent_container">
    <div class="header_container">
     <div class="header_logo col-xs-2">
      <a class="logo" href="https://www.macrotrends.net/" title="MacroTrends Home Page">
       <img src="./GDP by Country _ MacroTrends_files/logo_bright1.png"/>
      </a>
     </div>
     <div class="col-xs-5 pull-right" style="padding-top:8px;">
      <form>
       <div class="typeahead__container" style="z-index: 1041; position: relative;">
        <div class="typeahead__field">
         <span class="typeahead__query">
          <span class="typeahead__cancel-button">
           ×
          </span>
          <span class="typeahead__cancel-button">
           ×
          </span>
          <input autocomplete="off" autofocus="" class="js-typeahead" name="q" placeholder="Search over 200,000 charts..." type="search"/>
         </span>
         <span class="typeahead__button">
          <button type="submit">
           <span class="typeahead__search-icon">
           </span>
          </button>
         </span>
        </div>
        <div class="typeahead__result">
        </div>
       </div>
       <div class="typeahead__backdrop" style="opacity: 0.6; position: fixed; inset: 0px; z-index: 1040; background-color: rgb(255, 255, 255);">
       </div>
      </form>
     </div>
    </div>
   </div>
   <div class="menu_parent_container">
    <div class="menu_container">
     <div class="dropdown">
      <button class="dropbtn">
       Markets
      </button>
      <div class="dropdown-content">
       <a href="https://www.macrotrends.net/charts/stock-indexes">
        <div class="menu_item">
         Market Indexes
        </div>
       </a>
       <a href="https://www.macrotrends.net/charts/precious-metals">
        <div class="menu_item">
         Precious Metals
        </div>
       </a>
       <a href="https://www.macrotrends.net/charts/energy">
        <div class="menu_item">
         Energy
        </div>
       </a>
       <a href="https://www.macrotrends.net/charts/commodities">
        <div class="menu_item">
         Commodities
        </div>
       </a>
       <a href="https://www.macrotrends.net/charts/exchange-rates">
        <div class="menu_item">
         Exchange Rates
        </div>
       </a>
       <a href="https://www.macrotrends.net/charts/interest-rates">
        <div class="menu_item">
         Interest Rates
        </div>
       </a>
       <a href="https://www.macrotrends.net/futures">
        <div class="menu_item">
         Futures
        </div>
       </a>
      </div>
     </div>
     <div class="dropdown">
      <button class="dropbtn">
       Stock Research
      </button>
      <div class="dropdown-content">
       <a href="https://www.macrotrends.net/stocks/research">
        <div class="menu_item">
         Top Stocks
        </div>
       </a>
       <a href="https://www.macrotrends.net/stocks/stock-screener">
        <div class="menu_item">
         Stock Screener
        </div>
       </a>
      </div>
     </div>
     <div class="dropdown">
      <button class="dropbtn">
       Economy
      </button>
      <div class="dropdown-content">
       <a href="https://www.macrotrends.net/charts/economy">
        <div class="menu_item">
         U.S. Economic Charts
        </div>
       </a>
       <a href="https://www.macrotrends.net/global-metrics/countries/ranking/gdp-gross-domestic-product">
        GDP by Country
       </a>
       <a href="https://www.macrotrends.net/global-metrics/countries/ranking/gdp-per-capita">
        GDP Per Capita by Country
       </a>
       <a href="https://www.macrotrends.net/global-metrics/countries/ranking/manufacturing-output">
        Manufacturing by Country
       </a>
       <a href="https://www.macrotrends.net/global-metrics/countries/ranking/debt-to-gdp-ratio">
        Debt to GDP Ratio by Country
       </a>
      </div>
     </div>
     <div class="dropdown">
      <button class="dropbtn">
       Global Metrics
      </button>
      <div class="dropdown-content">
       <a href="https://www.macrotrends.net/global-metrics/countries/topic-overview">
        Topic Overview
       </a>
       <a href="https://www.macrotrends.net/global-metrics/countries/ranking/population">
        Largest Countries by Population
       </a>
       <a href="https://www.macrotrends.net/global-metrics/states/us-states-by-population">
        U.S. States by Population
       </a>
       <a href="https://www.macrotrends.net/global-metrics/cities/largest-cities-by-population">
        U.S. and World Cities by Population
       </a>
      </div>
     </div>
    </div>
   </div>
  </div>
  <div class="main_content_container container-fluid" id="main_content_container">
   <h1 style="margin-bottom:20px;">
    <strong>
     GDP by Country
    </strong>
   </h1>
   <div class="navigation_tabs" style="margin-bottom:20px;">
    <ul class="nav nav-tabs" id="myTabs" style="font-size:15px;">
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/population">
       Population
      </a>
     </li>
     <li class="active">
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/gdp-gross-domestic-product">
       Economy
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/trade-balance-deficit">
       Trade
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/healthcare-spending">
       Health
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/literacy-rate">
       Education
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/poverty-rate">
       Development
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/unemployment-rate">
       Labor Force
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/carbon-co2-emissions">
       Environment
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/crime-rate-statistics">
       Crime
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/immigration-statistics">
       Immigration
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/military-spending-defense-budget">
       Other
      </a>
     </li>
    </ul>
    <ul class="nav nav-tabs" id="myTabs" style="font-size:15px;">
     <li class="active">
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/gdp-gross-domestic-product">
       GDP
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/gdp-growth-rate">
       GDP Growth Rate
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/gdp-per-capita">
       GDP Per Capita
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/gni-gross-national-income">
       GNI
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/gni-per-capita">
       GNI Per Capita
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/debt-to-gdp-ratio">
       Debt to GDP
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/gnp-gross-national-product">
       GNP
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/inflation-rate-cpi">
       Inflation Rate
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/economic-growth-rate">
       Economic Growth
      </a>
     </li>
     <li>
      <a href="https://www.macrotrends.net/global-metrics/countries/ranking/manufacturing-output">
       Manufacturing
      </a>
     </li>
    </ul>
    <div style="background-color:#fff; margin: 20px 0px 20px 0px; padding:20px 30px; border:1px solid #dfdfdf; text-align:left;">
     <span style="color:#444; line-height: 1.8;">
      GDP at purchaser's prices is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources. Data are in current U.S. dollars. Dollar figures for GDP are converted from domestic currencies using single year official exchange rates. For a few countries where the official exchange rate does not reflect the rate effectively applied to actual foreign exchange transactions, an alternative conversion factor is used.
     </span>
    </div>
   </div>
   <div class="col-xs-12">
    <div style="background-color:#fff; margin: 30px 15px">
     <table class="table table-striped table-hover table-bordered" id="country_ranking">
      <thead>
       <tr>
        <th style="text-align:left;">
         Country Name
        </th>
        <th style="text-align:center;">
         2023
        </th>
        <th style="text-align:center;">
         2022
        </th>
        <th style="text-align:center;">
         2021
        </th>
        <th style="text-align:center;">
         2020
        </th>
        <th style="text-align:center;">
         2019
        </th>
       </tr>
      </thead>
      <tbody>
       <tr>
        <td style="text-align:left">
         <a href="https://www.macrotrends.net/global-metrics/countries/USA/united-states/gdp-gross-domestic-product">
          United States
         </a>
        </td>
        <td style="text-align:right;">
         $27,360,935,000,000
        </td>
        <td style="text-align:right;">
         $25,744,108,000,000
        </td>
        <td style="text-align:right;">
         $23,594,031,000,000
        </td>
        <td style="text-align:right;">
         $21,322,950,000,000
        </td>
        <td style="text-align:right;">
         $21,521,395,000,000
        </td>
       </tr>
       <tr>
        <td style="text-align:left">
         <a href="https://www.macrotrends.net/global-metrics/countries/CHN/china/gdp-gross-domestic-product">
          China
         </a>
        </td>
        <td style="text-align:right;">
         $17,794,781,986,105
        </td>
        <td style="text-align:right;">
         $17,881,783,387,001
        </td>
        <td style="text-align:right;">
         $17,820,459,508,852
        </td>
        <td style="text-align:right;">
         $14,687,744,162,801
        </td>
        <td style="text-align:right;">
         $14,279,968,506,272
        </td>
       </tr>
       <tr>
        <td style="text-align:left">
         <a href="https://www.macrotrends.net/global-metrics/countries/DEU/germany/gdp-gross-domestic-product">
          Germany
         </a>
        </td>
        <td style="text-align:right;">
         $4,456,081,016,706
        </td>
        <td style="text-align:right;">
         $4,082,469,490,798
        </td>
        <td style="text-align:right;">
         $4,278,503,934,690
        </td>
        <td style="text-align:right;">
         $3,887,727,161,914
        </td>
        <td style="text-align:right;">
         $3,889,177,589,255
        </td>
       </tr>
       <tr>
        <td style="text-align:left">
         <a href="https://www.macrotrends.net/global-metrics/countries/JPN/japan/gdp-gross-domestic-product">
          Japan
         </a>
        </td>
        <td style="text-align:right;">
         $4,212,945,159,781
        </td>
        <td style="text-align:right;">
         $4,256,410,760,724
        </td>
        <td style="text-align:right;">
         $5,034,620,784,585
        </td>
        <td style="text-align:right;">
         $5,055,587,093,502
        </td>
        <td style="text-align:right;">
         $5,117,993,853,017
        </td>
       </tr>
       <tr>
        <td style="text-align:left">
         <a href="https://www.macrotrends.net/global-metrics/countries/IND/india/gdp-gross-domestic-product">
          India
         </a>
        </td>
        <td style="text-align:right;">
         $3,549,918,918,778
        </td>
        <td style="text-align:right;">
         $3,353,470,496,886
        </td>
        <td style="text-align:right;">
         $3,167,270,623,261
        </td>
        <td style="text-align:right;">
         $2,674,851,578,587
        </td>
        <td style="text-align:right;">
         $2,835,606,256,559
        </td>
       </tr>
       <tr>
        <td style="text-align:left">
         <a href="https://www.macrotrends.net/global-metrics/countries/GBR/united-kingdom/gdp-gross-domestic-product">
          United Kingdom
         </a>
        </td>
        <td style="text-align:right;">
         $3,340,032,380,668
        </td>
        <td style="text-align:right;">
         $3,088,839,763,445
        </td>
        <td style="text-align:right;">
         $3,141,506,156,619
        </td>
        <td style="text-align:right;">
         $2,697,806,592,294
        </td>
        <td style="text-align:right;">
         $2,851,407,164,908
        </td>
       </tr>
       <tr>
        <td style="text-align:left">
         <a href="https://www.macrotrends.net/global-metrics/countries/FRA/france/gdp-gross-domestic-product">
          France
         </a>
        </td>
        <td style="text-align:right;">

In [52]:
# Count the number of tables

print("The number of tables are: {}".format(len(tables)))

NameError: name 'tables' is not defined

In [132]:
# Find the table (since there is only 1 on the page, I can use find_all)
Soup.find_all('table')

[<table class="table table-striped table-hover table-bordered" id="country_ranking">
 <thead>
 <tr>
 <th style="text-align:left;">Country Name</th>
 <th style="text-align:center;">2023</th>
 <th style="text-align:center;">2022</th>
 <th style="text-align:center;">2021</th>
 <th style="text-align:center;">2020</th>
 <th style="text-align:center;">2019</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/USA/united-states/gdp-gross-domestic-product">United States</a></td>
 <td style="text-align:right;">$27,360,935,000,000</td>
 <td style="text-align:right;">$25,744,108,000,000</td>
 <td style="text-align:right;">$23,594,031,000,000</td>
 <td style="text-align:right;">$21,322,950,000,000</td>
 <td style="text-align:right;">$21,521,395,000,000</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/CHN/china/gdp-gross-domestic-product">China</a></td>
 <td style="text-align:right;">$17,794,781,986,105</td>
 <td style="text-align:right;">$17,881,783,387,001</td>
 <td style="text-align:right;">$17,820,459,508,852</td>
 <td style="text-align:right;">$14,687,744,162,801</td>
 <td style="text-align:right;">$14,279,968,506,272</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/DEU/germany/gdp-gross-domestic-product">Germany</a></td>
 <td style="text-align:right;">$4,456,081,016,706</td>
 <td style="text-align:right;">$4,082,469,490,798</td>
 <td style="text-align:right;">$4,278,503,934,690</td>
 <td style="text-align:right;">$3,887,727,161,914</td>
 <td style="text-align:right;">$3,889,177,589,255</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/JPN/japan/gdp-gross-domestic-product">Japan</a></td>
 <td style="text-align:right;">$4,212,945,159,781</td>
 <td style="text-align:right;">$4,256,410,760,724</td>
 <td style="text-align:right;">$5,034,620,784,585</td>
 <td style="text-align:right;">$5,055,587,093,502</td>
 <td style="text-align:right;">$5,117,993,853,017</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/IND/india/gdp-gross-domestic-product">India</a></td>
 <td style="text-align:right;">$3,549,918,918,778</td>
 <td style="text-align:right;">$3,353,470,496,886</td>
 <td style="text-align:right;">$3,167,270,623,261</td>
 <td style="text-align:right;">$2,674,851,578,587</td>
 <td style="text-align:right;">$2,835,606,256,559</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/GBR/united-kingdom/gdp-gross-domestic-product">United Kingdom</a></td>
 <td style="text-align:right;">$3,340,032,380,668</td>
 <td style="text-align:right;">$3,088,839,763,445</td>
 <td style="text-align:right;">$3,141,506,156,619</td>
 <td style="text-align:right;">$2,697,806,592,294</td>
 <td style="text-align:right;">$2,851,407,164,908</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/FRA/france/gdp-gross-domestic-product">France</a></td>
 <td style="text-align:right;">$3,030,904,089,608</td>
 <td style="text-align:right;">$2,779,092,236,506</td>
 <td style="text-align:right;">$2,959,355,819,171</td>
 <td style="text-align:right;">$2,647,418,691,598</td>
 <td style="text-align:right;">$2,728,870,246,706</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ITA/italy/gdp-gross-domestic-product">Italy</a></td>
 <td style="text-align:right;">$2,254,851,212,732</td>
 <td style="text-align:right;">$2,066,972,096,554</td>
 <td style="text-align:right;">$2,154,875,493,745</td>
 <td style="text-align:right;">$1,897,461,635,592</td>
 <td style="text-align:right;">$2,011,302,198,827</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/BRA/brazil/gdp-gross-domestic-product">Brazil</a></td>
 <td style="text-align:right;">$2,173,665,655,937</td>
 <td style="text-align:right;">$1,951,923,942,083</td>
 <td style="text-align:right;">$1,670,647,399,035</td>
 <td style="text-align:right;">$1,476,107,231,194</td>
 <td style="text-align:right;">$1,873,288,205,186</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/CAN/canada/gdp-gross-domestic-product">Canada</a></td>
 <td style="text-align:right;">$2,140,085,567,791</td>
 <td style="text-align:right;">$2,161,483,369,422</td>
 <td style="text-align:right;">$2,007,472,181,464</td>
 <td style="text-align:right;">$1,655,684,730,000</td>
 <td style="text-align:right;">$1,743,725,183,673</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/RUS/russia/gdp-gross-domestic-product">Russia</a></td>
 <td style="text-align:right;">$2,021,421,476,035</td>
 <td style="text-align:right;">$2,266,029,240,645</td>
 <td style="text-align:right;">$1,843,392,293,734</td>
 <td style="text-align:right;">$1,493,075,894,362</td>
 <td style="text-align:right;">$1,693,115,002,708</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/MEX/mexico/gdp-gross-domestic-product">Mexico</a></td>
 <td style="text-align:right;">$1,788,886,821,047</td>
 <td style="text-align:right;">$1,463,323,889,037</td>
 <td style="text-align:right;">$1,313,069,763,987</td>
 <td style="text-align:right;">$1,120,832,412,469</td>
 <td style="text-align:right;">$1,305,211,135,823</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/AUS/australia/gdp-gross-domestic-product">Australia</a></td>
 <td style="text-align:right;">$1,723,827,215,335</td>
 <td style="text-align:right;">$1,692,956,646,856</td>
 <td style="text-align:right;">$1,559,033,756,285</td>
 <td style="text-align:right;">$1,330,381,544,909</td>
 <td style="text-align:right;">$1,394,671,325,961</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/KOR/south-korea/gdp-gross-domestic-product">South Korea</a></td>
 <td style="text-align:right;">$1,712,792,854,202</td>
 <td style="text-align:right;">$1,673,916,511,800</td>
 <td style="text-align:right;">$1,818,432,106,880</td>
 <td style="text-align:right;">$1,644,312,831,906</td>
 <td style="text-align:right;">$1,651,422,932,448</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ESP/spain/gdp-gross-domestic-product">Spain</a></td>
 <td style="text-align:right;">$1,580,694,712,516</td>
 <td style="text-align:right;">$1,417,800,466,263</td>
 <td style="text-align:right;">$1,445,651,653,605</td>
 <td style="text-align:right;">$1,278,128,867,875</td>
 <td style="text-align:right;">$1,394,320,055,129</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/IDN/indonesia/gdp-gross-domestic-product">Indonesia</a></td>
 <td style="text-align:right;">$1,371,171,152,331</td>
 <td style="text-align:right;">$1,319,076,267,310</td>
 <td style="text-align:right;">$1,186,509,691,087</td>
 <td style="text-align:right;">$1,059,054,842,698</td>
 <td style="text-align:right;">$1,119,099,871,350</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/NLD/netherlands/gdp-gross-domestic-product">Netherlands</a></td>
 <td style="text-align:right;">$1,118,124,749,886</td>
 <td style="text-align:right;">$1,009,398,719,033</td>
 <td style="text-align:right;">$1,029,678,338,329</td>
 <td style="text-align:right;">$909,793,466,661</td>
 <td style="text-align:right;">$910,194,347,569</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/TUR/turkey/gdp-gross-domestic-product">Turkey</a></td>
 <td style="text-align:right;">$1,108,022,373,260</td>
 <td style="text-align:right;">$907,118,435,953</td>
 <td style="text-align:right;">$819,865,253,670</td>
 <td style="text-align:right;">$720,338,498,175</td>
 <td style="text-align:right;">$761,005,946,788</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/SAU/saudi-arabia/gdp-gross-domestic-product">Saudi Arabia</a></td>
 <td style="text-align:right;">$1,067,582,933,333</td>
 <td style="text-align:right;">$1,108,571,466,667</td>
 <td style="text-align:right;">$874,156,000,000</td>
 <td style="text-align:right;">$734,271,200,000</td>
 <td style="text-align:right;">$838,564,800,000</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/CHE/switzerland/gdp-gross-domestic-product">Switzerland</a></td>
 <td style="text-align:right;">$884,940,402,230</td>
 <td style="text-align:right;">$818,426,550,206</td>
 <td style="text-align:right;">$813,408,787,222</td>
 <td style="text-align:right;">$741,999,406,006</td>
 <td style="text-align:right;">$721,369,112,727</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/POL/poland/gdp-gross-domestic-product">Poland</a></td>
 <td style="text-align:right;">$811,229,100,688</td>
 <td style="text-align:right;">$689,763,329,458</td>
 <td style="text-align:right;">$681,346,077,609</td>
 <td style="text-align:right;">$599,442,732,365</td>
 <td style="text-align:right;">$596,058,473,059</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ARG/argentina/gdp-gross-domestic-product">Argentina</a></td>
 <td style="text-align:right;">$640,591,410,664</td>
 <td style="text-align:right;">$631,133,384,440</td>
 <td style="text-align:right;">$487,902,572,164</td>
 <td style="text-align:right;">$385,740,508,437</td>
 <td style="text-align:right;">$447,754,683,615</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/BEL/belgium/gdp-gross-domestic-product">Belgium</a></td>
 <td style="text-align:right;">$632,216,577,075</td>
 <td style="text-align:right;">$583,613,982,019</td>
 <td style="text-align:right;">$600,904,461,226</td>
 <td style="text-align:right;">$526,021,513,474</td>
 <td style="text-align:right;">$535,865,804,350</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/SWE/sweden/gdp-gross-domestic-product">Sweden</a></td>
 <td style="text-align:right;">$593,267,701,033</td>
 <td style="text-align:right;">$590,409,594,949</td>
 <td style="text-align:right;">$639,714,956,069</td>
 <td style="text-align:right;">$547,054,174,236</td>
 <td style="text-align:right;">$533,879,529,188</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/IRL/ireland/gdp-gross-domestic-product">Ireland</a></td>
 <td style="text-align:right;">$545,629,450,404</td>
 <td style="text-align:right;">$533,140,011,838</td>
 <td style="text-align:right;">$513,391,778,883</td>
 <td style="text-align:right;">$428,608,687,830</td>
 <td style="text-align:right;">$398,933,010,007</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/AUT/austria/gdp-gross-domestic-product">Austria</a></td>
 <td style="text-align:right;">$516,034,144,116</td>
 <td style="text-align:right;">$470,941,926,751</td>
 <td style="text-align:right;">$479,295,362,747</td>
 <td style="text-align:right;">$435,049,316,956</td>
 <td style="text-align:right;">$444,596,155,845</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/THA/thailand/gdp-gross-domestic-product">Thailand</a></td>
 <td style="text-align:right;">$514,944,993,834</td>
 <td style="text-align:right;">$495,645,210,973</td>
 <td style="text-align:right;">$506,256,494,297</td>
 <td style="text-align:right;">$500,461,898,480</td>
 <td style="text-align:right;">$543,976,691,794</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ISR/israel/gdp-gross-domestic-product">Israel</a></td>
 <td style="text-align:right;">$509,901,495,702</td>
 <td style="text-align:right;">$525,002,447,653</td>
 <td style="text-align:right;">$488,526,545,879</td>
 <td style="text-align:right;">$413,267,669,232</td>
 <td style="text-align:right;">$402,470,513,619</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ARE/uae/gdp-gross-domestic-product">UAE</a></td>
 <td style="text-align:right;">$504,173,451,327</td>
 <td style="text-align:right;">$507,063,968,278</td>
 <td style="text-align:right;">$415,178,792,757</td>
 <td style="text-align:right;">$349,473,015,330</td>
 <td style="text-align:right;">$417,989,721,743</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/SGP/singapore/gdp-gross-domestic-product">Singapore</a></td>
 <td style="text-align:right;">$501,427,500,080</td>
 <td style="text-align:right;">$498,474,540,988</td>
 <td style="text-align:right;">$434,111,559,283</td>
 <td style="text-align:right;">$349,488,382,611</td>
 <td style="text-align:right;">$376,901,649,222</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/NOR/norway/gdp-gross-domestic-product">Norway</a></td>
 <td style="text-align:right;">$485,513,316,504</td>
 <td style="text-align:right;">$593,726,965,416</td>
 <td style="text-align:right;">$503,367,986,030</td>
 <td style="text-align:right;">$367,633,418,887</td>
 <td style="text-align:right;">$408,742,840,909</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/BGD/bangladesh/gdp-gross-domestic-product">Bangladesh</a></td>
 <td style="text-align:right;">$437,415,331,041</td>
 <td style="text-align:right;">$460,131,688,909</td>
 <td style="text-align:right;">$416,271,647,002</td>
 <td style="text-align:right;">$373,979,442,653</td>
 <td style="text-align:right;">$351,231,655,151</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/PHL/philippines/gdp-gross-domestic-product">Philippines</a></td>
 <td style="text-align:right;">$437,146,372,730</td>
 <td style="text-align:right;">$404,353,369,605</td>
 <td style="text-align:right;">$394,087,359,848</td>
 <td style="text-align:right;">$361,751,145,452</td>
 <td style="text-align:right;">$376,823,402,245</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/VNM/vietnam/gdp-gross-domestic-product">Vietnam</a></td>
 <td style="text-align:right;">$429,716,969,050</td>
 <td style="text-align:right;">$410,324,028,883</td>
 <td style="text-align:right;">$366,474,752,771</td>
 <td style="text-align:right;">$346,615,738,538</td>
 <td style="text-align:right;">$334,365,270,497</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/DNK/denmark/gdp-gross-domestic-product">Denmark</a></td>
 <td style="text-align:right;">$404,198,757,538</td>
 <td style="text-align:right;">$400,167,196,949</td>
 <td style="text-align:right;">$405,687,998,853</td>
 <td style="text-align:right;">$354,762,748,339</td>
 <td style="text-align:right;">$346,498,737,962</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/IRN/iran/gdp-gross-domestic-product">Iran</a></td>
 <td style="text-align:right;">$401,504,514,719</td>
 <td style="text-align:right;">$413,394,567,604</td>
 <td style="text-align:right;">$359,096,907,772</td>
 <td style="text-align:right;">$239,735,486,745</td>
 <td style="text-align:right;">$283,649,531,543</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/MYS/malaysia/gdp-gross-domestic-product">Malaysia</a></td>
 <td style="text-align:right;">$399,648,828,547</td>
 <td style="text-align:right;">$407,027,451,715</td>
 <td style="text-align:right;">$373,832,428,055</td>
 <td style="text-align:right;">$337,456,163,961</td>
 <td style="text-align:right;">$365,177,721,022</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/EGY/egypt/gdp-gross-domestic-product">Egypt</a></td>
 <td style="text-align:right;">$395,926,075,163</td>
 <td style="text-align:right;">$476,747,720,365</td>
 <td style="text-align:right;">$424,671,765,456</td>
 <td style="text-align:right;">$383,817,841,547</td>
 <td style="text-align:right;">$318,678,815,490</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/HKG/hong-kong/gdp-gross-domestic-product">Hong Kong</a></td>
 <td style="text-align:right;">$382,054,574,299</td>
 <td style="text-align:right;">$358,696,261,481</td>
 <td style="text-align:right;">$368,954,169,749</td>
 <td style="text-align:right;">$344,943,149,590</td>
 <td style="text-align:right;">$363,074,545,072</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ZAF/south-africa/gdp-gross-domestic-product">South Africa</a></td>
 <td style="text-align:right;">$377,781,600,986</td>
 <td style="text-align:right;">$405,270,850,099</td>
 <td style="text-align:right;">$420,117,812,466</td>
 <td style="text-align:right;">$338,291,396,027</td>
 <td style="text-align:right;">$389,330,032,224</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/COL/colombia/gdp-gross-domestic-product">Colombia</a></td>
 <td style="text-align:right;">$363,540,156,235</td>
 <td style="text-align:right;">$345,329,875,079</td>
 <td style="text-align:right;">$318,524,633,225</td>
 <td style="text-align:right;">$270,348,342,541</td>
 <td style="text-align:right;">$323,031,701,193</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/NGA/nigeria/gdp-gross-domestic-product">Nigeria</a></td>
 <td style="text-align:right;">$362,814,951,696</td>
 <td style="text-align:right;">$472,624,596,926</td>
 <td style="text-align:right;">$440,838,992,188</td>
 <td style="text-align:right;">$432,198,898,468</td>
 <td style="text-align:right;">$474,517,490,844</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ROU/romania/gdp-gross-domestic-product">Romania</a></td>
 <td style="text-align:right;">$351,002,579,630</td>
 <td style="text-align:right;">$298,891,515,898</td>
 <td style="text-align:right;">$285,810,244,502</td>
 <td style="text-align:right;">$251,362,514,350</td>
 <td style="text-align:right;">$251,017,797,625</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/PAK/pakistan/gdp-gross-domestic-product">Pakistan</a></td>
 <td style="text-align:right;">$338,368,455,318</td>
 <td style="text-align:right;">$374,787,958,882</td>
 <td style="text-align:right;">$348,516,647,445</td>
 <td style="text-align:right;">$300,425,609,818</td>
 <td style="text-align:right;">$320,909,472,771</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/CHL/chile/gdp-gross-domestic-product">Chile</a></td>
 <td style="text-align:right;">$335,533,331,669</td>
 <td style="text-align:right;">$302,116,539,409</td>
 <td style="text-align:right;">$315,515,014,839</td>
 <td style="text-align:right;">$254,042,159,309</td>
 <td style="text-align:right;">$278,285,058,719</td>
 </tr>
 <tr>
 <td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/CZE/czech-republic/gdp-gross-domestic-product">Czech Republic</a></td>

In [134]:
# Find that first table
table = Soup.find("table", {"id": "country_ranking"})
table

<table class="table table-striped table-hover table-bordered" id="country_ranking">
<thead>
<tr>
<th style="text-align:left;">Country Name</th>
<th style="text-align:center;">2023</th>
<th style="text-align:center;">2022</th>
<th style="text-align:center;">2021</th>
<th style="text-align:center;">2020</th>
<th style="text-align:center;">2019</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/USA/united-states/gdp-gross-domestic-product">United States</a></td>
<td style="text-align:right;">$27,360,935,000,000</td>
<td style="text-align:right;">$25,744,108,000,000</td>
<td style="text-align:right;">$23,594,031,000,000</td>
<td style="text-align:right;">$21,322,950,000,000</td>
<td style="text-align:right;">$21,521,395,000,000</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/CHN/china/gdp-gross-domestic-product">China</a></td>
<td style="text-align:right;">$17,794,781,986,105</td>
<td style="text-align:right;">$17,881,783,387,001</td>
<td style="text-align:right;">$17,820,459,508,852</td>
<td style="text-align:right;">$14,687,744,162,801</td>
<td style="text-align:right;">$14,279,968,506,272</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/DEU/germany/gdp-gross-domestic-product">Germany</a></td>
<td style="text-align:right;">$4,456,081,016,706</td>
<td style="text-align:right;">$4,082,469,490,798</td>
<td style="text-align:right;">$4,278,503,934,690</td>
<td style="text-align:right;">$3,887,727,161,914</td>
<td style="text-align:right;">$3,889,177,589,255</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/JPN/japan/gdp-gross-domestic-product">Japan</a></td>
<td style="text-align:right;">$4,212,945,159,781</td>
<td style="text-align:right;">$4,256,410,760,724</td>
<td style="text-align:right;">$5,034,620,784,585</td>
<td style="text-align:right;">$5,055,587,093,502</td>
<td style="text-align:right;">$5,117,993,853,017</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/IND/india/gdp-gross-domestic-product">India</a></td>
<td style="text-align:right;">$3,549,918,918,778</td>
<td style="text-align:right;">$3,353,470,496,886</td>
<td style="text-align:right;">$3,167,270,623,261</td>
<td style="text-align:right;">$2,674,851,578,587</td>
<td style="text-align:right;">$2,835,606,256,559</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/GBR/united-kingdom/gdp-gross-domestic-product">United Kingdom</a></td>
<td style="text-align:right;">$3,340,032,380,668</td>
<td style="text-align:right;">$3,088,839,763,445</td>
<td style="text-align:right;">$3,141,506,156,619</td>
<td style="text-align:right;">$2,697,806,592,294</td>
<td style="text-align:right;">$2,851,407,164,908</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/FRA/france/gdp-gross-domestic-product">France</a></td>
<td style="text-align:right;">$3,030,904,089,608</td>
<td style="text-align:right;">$2,779,092,236,506</td>
<td style="text-align:right;">$2,959,355,819,171</td>
<td style="text-align:right;">$2,647,418,691,598</td>
<td style="text-align:right;">$2,728,870,246,706</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ITA/italy/gdp-gross-domestic-product">Italy</a></td>
<td style="text-align:right;">$2,254,851,212,732</td>
<td style="text-align:right;">$2,066,972,096,554</td>
<td style="text-align:right;">$2,154,875,493,745</td>
<td style="text-align:right;">$1,897,461,635,592</td>
<td style="text-align:right;">$2,011,302,198,827</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/BRA/brazil/gdp-gross-domestic-product">Brazil</a></td>
<td style="text-align:right;">$2,173,665,655,937</td>
<td style="text-align:right;">$1,951,923,942,083</td>
<td style="text-align:right;">$1,670,647,399,035</td>
<td style="text-align:right;">$1,476,107,231,194</td>
<td style="text-align:right;">$1,873,288,205,186</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/CAN/canada/gdp-gross-domestic-product">Canada</a></td>
<td style="text-align:right;">$2,140,085,567,791</td>
<td style="text-align:right;">$2,161,483,369,422</td>
<td style="text-align:right;">$2,007,472,181,464</td>
<td style="text-align:right;">$1,655,684,730,000</td>
<td style="text-align:right;">$1,743,725,183,673</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/RUS/russia/gdp-gross-domestic-product">Russia</a></td>
<td style="text-align:right;">$2,021,421,476,035</td>
<td style="text-align:right;">$2,266,029,240,645</td>
<td style="text-align:right;">$1,843,392,293,734</td>
<td style="text-align:right;">$1,493,075,894,362</td>
<td style="text-align:right;">$1,693,115,002,708</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/MEX/mexico/gdp-gross-domestic-product">Mexico</a></td>
<td style="text-align:right;">$1,788,886,821,047</td>
<td style="text-align:right;">$1,463,323,889,037</td>
<td style="text-align:right;">$1,313,069,763,987</td>
<td style="text-align:right;">$1,120,832,412,469</td>
<td style="text-align:right;">$1,305,211,135,823</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/AUS/australia/gdp-gross-domestic-product">Australia</a></td>
<td style="text-align:right;">$1,723,827,215,335</td>
<td style="text-align:right;">$1,692,956,646,856</td>
<td style="text-align:right;">$1,559,033,756,285</td>
<td style="text-align:right;">$1,330,381,544,909</td>
<td style="text-align:right;">$1,394,671,325,961</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/KOR/south-korea/gdp-gross-domestic-product">South Korea</a></td>
<td style="text-align:right;">$1,712,792,854,202</td>
<td style="text-align:right;">$1,673,916,511,800</td>
<td style="text-align:right;">$1,818,432,106,880</td>
<td style="text-align:right;">$1,644,312,831,906</td>
<td style="text-align:right;">$1,651,422,932,448</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ESP/spain/gdp-gross-domestic-product">Spain</a></td>
<td style="text-align:right;">$1,580,694,712,516</td>
<td style="text-align:right;">$1,417,800,466,263</td>
<td style="text-align:right;">$1,445,651,653,605</td>
<td style="text-align:right;">$1,278,128,867,875</td>
<td style="text-align:right;">$1,394,320,055,129</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/IDN/indonesia/gdp-gross-domestic-product">Indonesia</a></td>
<td style="text-align:right;">$1,371,171,152,331</td>
<td style="text-align:right;">$1,319,076,267,310</td>
<td style="text-align:right;">$1,186,509,691,087</td>
<td style="text-align:right;">$1,059,054,842,698</td>
<td style="text-align:right;">$1,119,099,871,350</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/NLD/netherlands/gdp-gross-domestic-product">Netherlands</a></td>
<td style="text-align:right;">$1,118,124,749,886</td>
<td style="text-align:right;">$1,009,398,719,033</td>
<td style="text-align:right;">$1,029,678,338,329</td>
<td style="text-align:right;">$909,793,466,661</td>
<td style="text-align:right;">$910,194,347,569</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/TUR/turkey/gdp-gross-domestic-product">Turkey</a></td>
<td style="text-align:right;">$1,108,022,373,260</td>
<td style="text-align:right;">$907,118,435,953</td>
<td style="text-align:right;">$819,865,253,670</td>
<td style="text-align:right;">$720,338,498,175</td>
<td style="text-align:right;">$761,005,946,788</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/SAU/saudi-arabia/gdp-gross-domestic-product">Saudi Arabia</a></td>
<td style="text-align:right;">$1,067,582,933,333</td>
<td style="text-align:right;">$1,108,571,466,667</td>
<td style="text-align:right;">$874,156,000,000</td>
<td style="text-align:right;">$734,271,200,000</td>
<td style="text-align:right;">$838,564,800,000</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/CHE/switzerland/gdp-gross-domestic-product">Switzerland</a></td>
<td style="text-align:right;">$884,940,402,230</td>
<td style="text-align:right;">$818,426,550,206</td>
<td style="text-align:right;">$813,408,787,222</td>
<td style="text-align:right;">$741,999,406,006</td>
<td style="text-align:right;">$721,369,112,727</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/POL/poland/gdp-gross-domestic-product">Poland</a></td>
<td style="text-align:right;">$811,229,100,688</td>
<td style="text-align:right;">$689,763,329,458</td>
<td style="text-align:right;">$681,346,077,609</td>
<td style="text-align:right;">$599,442,732,365</td>
<td style="text-align:right;">$596,058,473,059</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ARG/argentina/gdp-gross-domestic-product">Argentina</a></td>
<td style="text-align:right;">$640,591,410,664</td>
<td style="text-align:right;">$631,133,384,440</td>
<td style="text-align:right;">$487,902,572,164</td>
<td style="text-align:right;">$385,740,508,437</td>
<td style="text-align:right;">$447,754,683,615</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/BEL/belgium/gdp-gross-domestic-product">Belgium</a></td>
<td style="text-align:right;">$632,216,577,075</td>
<td style="text-align:right;">$583,613,982,019</td>
<td style="text-align:right;">$600,904,461,226</td>
<td style="text-align:right;">$526,021,513,474</td>
<td style="text-align:right;">$535,865,804,350</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/SWE/sweden/gdp-gross-domestic-product">Sweden</a></td>
<td style="text-align:right;">$593,267,701,033</td>
<td style="text-align:right;">$590,409,594,949</td>
<td style="text-align:right;">$639,714,956,069</td>
<td style="text-align:right;">$547,054,174,236</td>
<td style="text-align:right;">$533,879,529,188</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/IRL/ireland/gdp-gross-domestic-product">Ireland</a></td>
<td style="text-align:right;">$545,629,450,404</td>
<td style="text-align:right;">$533,140,011,838</td>
<td style="text-align:right;">$513,391,778,883</td>
<td style="text-align:right;">$428,608,687,830</td>
<td style="text-align:right;">$398,933,010,007</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/AUT/austria/gdp-gross-domestic-product">Austria</a></td>
<td style="text-align:right;">$516,034,144,116</td>
<td style="text-align:right;">$470,941,926,751</td>
<td style="text-align:right;">$479,295,362,747</td>
<td style="text-align:right;">$435,049,316,956</td>
<td style="text-align:right;">$444,596,155,845</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/THA/thailand/gdp-gross-domestic-product">Thailand</a></td>
<td style="text-align:right;">$514,944,993,834</td>
<td style="text-align:right;">$495,645,210,973</td>
<td style="text-align:right;">$506,256,494,297</td>
<td style="text-align:right;">$500,461,898,480</td>
<td style="text-align:right;">$543,976,691,794</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ISR/israel/gdp-gross-domestic-product">Israel</a></td>
<td style="text-align:right;">$509,901,495,702</td>
<td style="text-align:right;">$525,002,447,653</td>
<td style="text-align:right;">$488,526,545,879</td>
<td style="text-align:right;">$413,267,669,232</td>
<td style="text-align:right;">$402,470,513,619</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ARE/uae/gdp-gross-domestic-product">UAE</a></td>
<td style="text-align:right;">$504,173,451,327</td>
<td style="text-align:right;">$507,063,968,278</td>
<td style="text-align:right;">$415,178,792,757</td>
<td style="text-align:right;">$349,473,015,330</td>
<td style="text-align:right;">$417,989,721,743</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/SGP/singapore/gdp-gross-domestic-product">Singapore</a></td>
<td style="text-align:right;">$501,427,500,080</td>
<td style="text-align:right;">$498,474,540,988</td>
<td style="text-align:right;">$434,111,559,283</td>
<td style="text-align:right;">$349,488,382,611</td>
<td style="text-align:right;">$376,901,649,222</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/NOR/norway/gdp-gross-domestic-product">Norway</a></td>
<td style="text-align:right;">$485,513,316,504</td>
<td style="text-align:right;">$593,726,965,416</td>
<td style="text-align:right;">$503,367,986,030</td>
<td style="text-align:right;">$367,633,418,887</td>
<td style="text-align:right;">$408,742,840,909</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/BGD/bangladesh/gdp-gross-domestic-product">Bangladesh</a></td>
<td style="text-align:right;">$437,415,331,041</td>
<td style="text-align:right;">$460,131,688,909</td>
<td style="text-align:right;">$416,271,647,002</td>
<td style="text-align:right;">$373,979,442,653</td>
<td style="text-align:right;">$351,231,655,151</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/PHL/philippines/gdp-gross-domestic-product">Philippines</a></td>
<td style="text-align:right;">$437,146,372,730</td>
<td style="text-align:right;">$404,353,369,605</td>
<td style="text-align:right;">$394,087,359,848</td>
<td style="text-align:right;">$361,751,145,452</td>
<td style="text-align:right;">$376,823,402,245</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/VNM/vietnam/gdp-gross-domestic-product">Vietnam</a></td>
<td style="text-align:right;">$429,716,969,050</td>
<td style="text-align:right;">$410,324,028,883</td>
<td style="text-align:right;">$366,474,752,771</td>
<td style="text-align:right;">$346,615,738,538</td>
<td style="text-align:right;">$334,365,270,497</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/DNK/denmark/gdp-gross-domestic-product">Denmark</a></td>
<td style="text-align:right;">$404,198,757,538</td>
<td style="text-align:right;">$400,167,196,949</td>
<td style="text-align:right;">$405,687,998,853</td>
<td style="text-align:right;">$354,762,748,339</td>
<td style="text-align:right;">$346,498,737,962</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/IRN/iran/gdp-gross-domestic-product">Iran</a></td>
<td style="text-align:right;">$401,504,514,719</td>
<td style="text-align:right;">$413,394,567,604</td>
<td style="text-align:right;">$359,096,907,772</td>
<td style="text-align:right;">$239,735,486,745</td>
<td style="text-align:right;">$283,649,531,543</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/MYS/malaysia/gdp-gross-domestic-product">Malaysia</a></td>
<td style="text-align:right;">$399,648,828,547</td>
<td style="text-align:right;">$407,027,451,715</td>
<td style="text-align:right;">$373,832,428,055</td>
<td style="text-align:right;">$337,456,163,961</td>
<td style="text-align:right;">$365,177,721,022</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/EGY/egypt/gdp-gross-domestic-product">Egypt</a></td>
<td style="text-align:right;">$395,926,075,163</td>
<td style="text-align:right;">$476,747,720,365</td>
<td style="text-align:right;">$424,671,765,456</td>
<td style="text-align:right;">$383,817,841,547</td>
<td style="text-align:right;">$318,678,815,490</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/HKG/hong-kong/gdp-gross-domestic-product">Hong Kong</a></td>
<td style="text-align:right;">$382,054,574,299</td>
<td style="text-align:right;">$358,696,261,481</td>
<td style="text-align:right;">$368,954,169,749</td>
<td style="text-align:right;">$344,943,149,590</td>
<td style="text-align:right;">$363,074,545,072</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ZAF/south-africa/gdp-gross-domestic-product">South Africa</a></td>
<td style="text-align:right;">$377,781,600,986</td>
<td style="text-align:right;">$405,270,850,099</td>
<td style="text-align:right;">$420,117,812,466</td>
<td style="text-align:right;">$338,291,396,027</td>
<td style="text-align:right;">$389,330,032,224</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/COL/colombia/gdp-gross-domestic-product">Colombia</a></td>
<td style="text-align:right;">$363,540,156,235</td>
<td style="text-align:right;">$345,329,875,079</td>
<td style="text-align:right;">$318,524,633,225</td>
<td style="text-align:right;">$270,348,342,541</td>
<td style="text-align:right;">$323,031,701,193</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/NGA/nigeria/gdp-gross-domestic-product">Nigeria</a></td>
<td style="text-align:right;">$362,814,951,696</td>
<td style="text-align:right;">$472,624,596,926</td>
<td style="text-align:right;">$440,838,992,188</td>
<td style="text-align:right;">$432,198,898,468</td>
<td style="text-align:right;">$474,517,490,844</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/ROU/romania/gdp-gross-domestic-product">Romania</a></td>
<td style="text-align:right;">$351,002,579,630</td>
<td style="text-align:right;">$298,891,515,898</td>
<td style="text-align:right;">$285,810,244,502</td>
<td style="text-align:right;">$251,362,514,350</td>
<td style="text-align:right;">$251,017,797,625</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/PAK/pakistan/gdp-gross-domestic-product">Pakistan</a></td>
<td style="text-align:right;">$338,368,455,318</td>
<td style="text-align:right;">$374,787,958,882</td>
<td style="text-align:right;">$348,516,647,445</td>
<td style="text-align:right;">$300,425,609,818</td>
<td style="text-align:right;">$320,909,472,771</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/CHL/chile/gdp-gross-domestic-product">Chile</a></td>
<td style="text-align:right;">$335,533,331,669</td>
<td style="text-align:right;">$302,116,539,409</td>
<td style="text-align:right;">$315,515,014,839</td>
<td style="text-align:right;">$254,042,159,309</td>
<td style="text-align:right;">$278,285,058,719</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/CZE/czech-republic/gdp-gross-domestic-product">Czech Republic</a></td>
<td style="text-align:right;">$330,858,339,872</td>
<td style="text-align:right;">$290,565,654,836</td>
<td style="text-align:right;">$281,791,218,507</td>
<td style="text-align:right;">$245,974,558,654</td>
<td style="text-align:right;">$252,548,179,965</td>
</tr>
<tr>
<td style="text-align:left"><a href="https://www.macrotrends.net/global-metrics/countries/FIN/finland/gdp-gross-domestic-product">Finland</a></td>

In [136]:
# Find the headers
headers = [th.text.strip() for th in table.find("thead").find_all("th")]

headers

['Country Name', '2023', '2022', '2021', '2020', '2019']

In [138]:
row_data = []

if table:
    for tr in table.find("tbody").find_all("tr"):
        cells = [td.text.strip() for td in tr.find_all("td")]
        row_data.append(cells)

row_data

[['United States',
  '$27,360,935,000,000',
  '$25,744,108,000,000',
  '$23,594,031,000,000',
  '$21,322,950,000,000',
  '$21,521,395,000,000'],
 ['China',
  '$17,794,781,986,105',
  '$17,881,783,387,001',
  '$17,820,459,508,852',
  '$14,687,744,162,801',
  '$14,279,968,506,272'],
 ['Germany',
  '$4,456,081,016,706',
  '$4,082,469,490,798',
  '$4,278,503,934,690',
  '$3,887,727,161,914',
  '$3,889,177,589,255'],
 ['Japan',
  '$4,212,945,159,781',
  '$4,256,410,760,724',
  '$5,034,620,784,585',
  '$5,055,587,093,502',
  '$5,117,993,853,017'],
 ['India',
  '$3,549,918,918,778',
  '$3,353,470,496,886',
  '$3,167,270,623,261',
  '$2,674,851,578,587',
  '$2,835,606,256,559'],
 ['United Kingdom',
  '$3,340,032,380,668',
  '$3,088,839,763,445',
  '$3,141,506,156,619',
  '$2,697,806,592,294',
  '$2,851,407,164,908'],
 ['France',
  '$3,030,904,089,608',
  '$2,779,092,236,506',
  '$2,959,355,819,171',
  '$2,647,418,691,598',
  '$2,728,870,246,706'],
 ['Italy',
  '$2,254,851,212,732',
  '$2,066,972,096,554',
  '$2,154,875,493,745',
  '$1,897,461,635,592',
  '$2,011,302,198,827'],
 ['Brazil',
  '$2,173,665,655,937',
  '$1,951,923,942,083',
  '$1,670,647,399,035',
  '$1,476,107,231,194',
  '$1,873,288,205,186'],
 ['Canada',
  '$2,140,085,567,791',
  '$2,161,483,369,422',
  '$2,007,472,181,464',
  '$1,655,684,730,000',
  '$1,743,725,183,673'],
 ['Russia',
  '$2,021,421,476,035',
  '$2,266,029,240,645',
  '$1,843,392,293,734',
  '$1,493,075,894,362',
  '$1,693,115,002,708'],
 ['Mexico',
  '$1,788,886,821,047',
  '$1,463,323,889,037',
  '$1,313,069,763,987',
  '$1,120,832,412,469',
  '$1,305,211,135,823'],
 ['Australia',
  '$1,723,827,215,335',
  '$1,692,956,646,856',
  '$1,559,033,756,285',
  '$1,330,381,544,909',
  '$1,394,671,325,961'],
 ['South Korea',
  '$1,712,792,854,202',
  '$1,673,916,511,800',
  '$1,818,432,106,880',
  '$1,644,312,831,906',
  '$1,651,422,932,448'],
 ['Spain',
  '$1,580,694,712,516',
  '$1,417,800,466,263',
  '$1,445,651,653,605',
  '$1,278,128,867,875',
  '$1,394,320,055,129'],
 ['Indonesia',
  '$1,371,171,152,331',
  '$1,319,076,267,310',
  '$1,186,509,691,087',
  '$1,059,054,842,698',
  '$1,119,099,871,350'],
 ['Netherlands',
  '$1,118,124,749,886',
  '$1,009,398,719,033',
  '$1,029,678,338,329',
  '$909,793,466,661',
  '$910,194,347,569'],
 ['Turkey',
  '$1,108,022,373,260',
  '$907,118,435,953',
  '$819,865,253,670',
  '$720,338,498,175',
  '$761,005,946,788'],
 ['Saudi Arabia',
  '$1,067,582,933,333',
  '$1,108,571,466,667',
  '$874,156,000,000',
  '$734,271,200,000',
  '$838,564,800,000'],
 ['Switzerland',
  '$884,940,402,230',
  '$818,426,550,206',
  '$813,408,787,222',
  '$741,999,406,006',
  '$721,369,112,727'],
 ['Poland',
  '$811,229,100,688',
  '$689,763,329,458',
  '$681,346,077,609',
  '$599,442,732,365',
  '$596,058,473,059'],
 ['Argentina',
  '$640,591,410,664',
  '$631,133,384,440',
  '$487,902,572,164',
  '$385,740,508,437',
  '$447,754,683,615'],
 ['Belgium',
  '$632,216,577,075',
  '$583,613,982,019',
  '$600,904,461,226',
  '$526,021,513,474',
  '$535,865,804,350'],
 ['Sweden',
  '$593,267,701,033',
  '$590,409,594,949',
  '$639,714,956,069',
  '$547,054,174,236',
  '$533,879,529,188'],
 ['Ireland',
  '$545,629,450,404',
  '$533,140,011,838',
  '$513,391,778,883',
  '$428,608,687,830',
  '$398,933,010,007'],
 ['Austria',
  '$516,034,144,116',
  '$470,941,926,751',
  '$479,295,362,747',
  '$435,049,316,956',
  '$444,596,155,845'],
 ['Thailand',
  '$514,944,993,834',
  '$495,645,210,973',
  '$506,256,494,297',
  '$500,461,898,480',
  '$543,976,691,794'],
 ['Israel',
  '$509,901,495,702',
  '$525,002,447,653',
  '$488,526,545,879',
  '$413,267,669,232',
  '$402,470,513,619'],
 ['UAE',
  '$504,173,451,327',
  '$507,063,968,278',
  '$415,178,792,757',
  '$349,473,015,330',
  '$417,989,721,743'],
 ['Singapore',
  '$501,427,500,080',
  '$498,474,540,988',
  '$434,111,559,283',
  '$349,488,382,611',
  '$376,901,649,222'],
 ['Norway',
  '$485,513,316,504',
  '$593,726,965,416',
  '$503,367,986,030',
  '$367,633,418,887',
  '$408,742,840,909'],
 ['Bangladesh',
  '$437,415,331,041',
  '$460,131,688,909',
  '$416,271,647,002',
  '$373,979,442,653',
  '$351,231,655,151'],
 ['Philippines',
  '$437,146,372,730',
  '$404,353,369,605',
  '$394,087,359,848',
  '$361,751,145,452',
  '$376,823,402,245'],
 ['Vietnam',
  '$429,716,969,050',
  '$410,324,028,883',
  '$366,474,752,771',
  '$346,615,738,538',
  '$334,365,270,497'],
 ['Denmark',
  '$404,198,757,538',
  '$400,167,196,949',
  '$405,687,998,853',
  '$354,762,748,339',
  '$346,498,737,962'],
 ['Iran',
  '$401,504,514,719',
  '$413,394,567,604',
  '$359,096,907,772',
  '$239,735,486,745',
  '$283,649,531,543'],
 ['Malaysia',
  '$399,648,828,547',
  '$407,027,451,715',
  '$373,832,428,055',
  '$337,456,163,961',
  '$365,177,721,022'],
 ['Egypt',
  '$395,926,075,163',
  '$476,747,720,365',
  '$424,671,765,456',
  '$383,817,841,547',
  '$318,678,815,490'],
 ['Hong Kong',
  '$382,054,574,299',
  '$358,696,261,481',
  '$368,954,169,749',
  '$344,943,149,590',
  '$363,074,545,072'],
 ['South Africa',
  '$377,781,600,986',
  '$405,270,850,099',
  '$420,117,812,466',
  '$338,291,396,027',
  '$389,330,032,224'],
 ['Colombia',
  '$363,540,156,235',
  '$345,329,875,079',
  '$318,524,633,225',
  '$270,348,342,541',
  '$323,031,701,193'],
 ['Nigeria',
  '$362,814,951,696',
  '$472,624,596,926',
  '$440,838,992,188',
  '$432,198,898,468',
  '$474,517,490,844'],
 ['Romania',
  '$351,002,579,630',
  '$298,891,515,898',
  '$285,810,244,502',
  '$251,362,514,350',
  '$251,017,797,625'],
 ['Pakistan',
  '$338,368,455,318',
  '$374,787,958,882',
  '$348,516,647,445',
  '$300,425,609,818',
  '$320,909,472,771'],
 ['Chile',
  '$335,533,331,669',
  '$302,116,539,409',
  '$315,515,014,839',
  '$254,042,159,309',
  '$278,285,058,719'],
 ['Czech Republic',
  '$330,858,339,872',
  '$290,565,654,836',
  '$281,791,218,507',
  '$245,974,558,654',
  '$252,548,179,965'],
 ['Finland',
  '$300,187,202,696',
  '$281,887,430,796',
  '$296,470,417,085',
  '$271,886,077,382',
  '$268,514,916,973'],
 ['Portugal',
  '$287,080,013,574',
  '$255,196,659,934',
  '$255,534,839,406',
  '$229,031,860,521',
  '$239,986,922,639'],
 ['Peru',
  '$267,603,248,655',
  '$246,488,757,636',
  '$226,354,278,281',
  '$201,409,694,756',
  '$228,346,006,004'],
 ['Kazakhstan',
  '$261,421,121,086',
  '$225,496,328,925',
  '$197,112,255,361',
  '$171,082,365,861',
  '$181,667,184,855'],
 ['New Zealand',
  '$253,465,703,232',
  '$246,733,522,841',
  '$253,644,079,785',
  '$212,697,530,898',
  '$212,846,907,683'],
 ['Iraq',
  '$250,842,782,139',
  '$286,640,340,966',
  '$209,691,945,713',
  '$180,898,797,936',
  '$233,636,097,800'],
 ['Algeria',
  '$239,899,491,128',
  '$225,560,256,622',
  '$186,265,418,571',
  '$164,873,415,325',
  '$193,459,662,091'],
 ['Greece',
  '$238,206,312,633',
  '$217,581,324,512',
  '$214,667,807,441',
  '$188,480,337,286',
  '$205,252,760,889'],
 ['Hungary',
  '$212,388,906,459',
  '$177,006,128,625',
  '$182,109,999,478',
  '$157,288,955,508',
  '$164,020,460,332'],
 ['Ukraine',
  '$178,757,021,387',
  '$161,989,520,721',
  '$199,765,859,571',
  '$156,617,722,013',
  '$153,883,047,510'],
 ['Ethiopia',
  '$163,697,927,594',
  '$126,772,703,048',
  '$111,261,882,958',
  '$107,657,734,392',
  '$95,912,607,722'],
 ['Kuwait',
  '$161,772,221,951',
  '$182,809,482,401',
  '$141,777,271,269',
  '$107,512,998,447',
  '$138,696,321,088'],
 ['Morocco',
  '$141,109,373,209',
  '$130,912,558,830',
  '$141,817,797,083',
  '$121,353,645,057',
  '$128,920,266,409'],
 ['Slovak Republic',
  '$132,793,622,283',
  '$115,584,743,574',
  '$118,563,266,602',
  '$106,737,868,874',
  '$105,711,680,181'],
 ['Dominican Republic',
  '$121,444,279,314',
  '$113,537,368,176',
  '$94,243,425,938',
  '$78,844,656,298',
  '$88,941,372,558'],
 ['Ecuador',
  '$118,844,826,000',
  '$116,586,079,000',
  '$107,435,101,000',
  '$95,865,472,000',
  '$107,595,829,000'],
 ['Puerto Rico',
  '$117,902,300,000',
  '$113,567,200,000',
  '$106,426,600,000',
  '$103,130,900,000',
  '$105,126,400,000'],
 ['Sudan',
  '$109,327,023,589',
  '$51,666,875,363',
  '$34,229,513,775',
  '$27,034,593,750',
  '$32,338,079,165'],
 ['Oman',
  '$108,192,457,737',
  '$114,667,360,208',
  '$88,191,977,373',
  '$75,909,397,659',
  '$88,060,858,257'],
 ['Kenya',
  '$107,440,575,838',
  '$113,419,826,114',
  '$109,703,658,905',
  '$100,657,505,751',
  '$100,378,436,207'],
 ['Guatemala',
  '$102,050,473,864',
  '$95,003,330,316',
  '$86,053,083,476',
  '$77,715,183,063',
  '$77,172,317,259'],
 ['Bulgaria',
  '$101,584,384,673',
  '$90,346,169,915',
  '$84,041,493,016',
  '$70,368,758,395',
  '$68,881,010,246'],
 ['Uzbekistan',
  '$90,889,149,307',
  '$81,140,823,252',
  '$69,600,614,987',
  '$60,224,701,297',
  '$60,283,503,705'],
 ['Costa Rica',
  '$86,497,941,439',
  '$69,243,626,029',
  '$64,960,725,734',
  '$62,395,610,760',
  '$64,417,670,521'],
 ['Luxembourg',
  '$85,755,006,124',
  '$81,641,807,866',
  '$85,584,105,994',
  '$73,699,366,700',
  '$69,890,505,324'],
 ['Angola',
  '$84,722,957,642',
  '$104,399,746,853',
  '$66,505,129,988',
  '$48,501,561,204',
  '$70,897,962,732'],
 ['Sri Lanka',
  '$84,356,860,421',
  '$74,144,875,098',
  '$88,609,332,762',
  '$84,304,298,771',
  '$89,014,978,344'],
 ['Panama',
  '$83,382,400,000',
  '$76,522,511,781',
  '$67,406,738,100',
  '$57,086,836,900',
  '$69,721,787,500'],
 ['Croatia',
  '$82,688,842,717',
  '$71,997,070,660',
  '$69,602,166,351',
  '$58,221,300,898',
  '$61,867,157,679'],
 ['Tanzania',
  '$79,158,286,334',
  '$75,769,974,505',
  '$70,655,628,148',
  '$66,068,737,786',
  '$61,026,731,926'],
 ['Lithuania',
  '$77,836,396,963',
  '$71,013,953,448',
  '$66,798,933,786',
  '$56,964,942,999',
  '$54,808,531,641'],
 ['Uruguay',
  '$77,240,831,587',
  '$70,164,683,290',
  '$60,760,798,596',
  '$53,668,636,568',
  '$62,222,387,929'],
 ['Ghana',
  '$76,370,394,412',
  '$74,263,364,042',
  '$79,524,421,861',
  '$70,043,095,504',
  '$68,337,969,248'],
 ['Serbia',
  '$75,187,125,427',
  '$63,563,410,721',
  '$63,101,042,898',
  '$53,356,484,591',
  '$51,514,242,939'],
 ['Azerbaijan',
  '$72,356,176,471',
  '$78,807,470,588',
  '$54,825,411,765',
  '$42,693,000,000',
  '$48,174,235,294'],
 ['Belarus',
  '$71,857,382,746',
  '$73,775,179,925',
  '$69,673,747,132',
  '$61,371,755,326',
  '$64,410,122,847'],
 ['Slovenia',
  '$68,216,781,411',
  '$60,063,475,466',
  '$61,832,201,544',
  '$53,734,526,854',
  '$54,386,654,314'],
 ['Democratic Republic Of Congo',
  '$66,383,287,003',
  '$65,801,547,620',
  '$55,328,482,784',
  '$48,716,961,860',
  '$51,775,829,877'],
 ['Myanmar',
  '$64,815,031,669',
  '$62,253,049,892',
  '$66,345,291,160',
  '$79,006,113,643',
  '$75,065,106,228'],
 ['Turkmenistan',
  '$59,887,334,844',
  '$56,542,857,143',
  '$50,007,428,571',
  '$45,818,000,000',
  '$45,232,857,143'],
 ['Jordan',
  '$50,813,642,349',
  '$48,653,381,831',
  '$46,296,100,141',
  '$43,700,383,099',
  '$44,502,816,901'],
 ['Libya',
  '$50,491,722,446',
  '$55,938,727,098',
  '$47,786,789,104',
  '$65,688,454,972',
  '$72,081,962,263'],
 ['Uganda',
  '$49,272,882,214',
  '$45,565,333,216',
  '$40,529,788,744',
  '$37,600,368,240',
  '$35,348,155,095'],
 ['Tunisia',
  '$48,529,595,417',
  '$44,579,761,023',
  '$46,812,290,143',
  '$42,491,816,476',
  '$41,905,540,184'],
 ['Cameroon',
  '$47,945,510,090',
  '$43,644,068,311',
  '$44,993,521,774',
  '$40,773,241,177',
  '$39,667,757,528'],
 ['Macao',
  '$47,061,843,716',
  '$24,464,719,190',
  '$30,969,334,705',
  '$25,343,525,936',
  '$55,082,293,844'],
 ['Bolivia',
  '$45,849,832,906',
  '$44,008,282,880',
  '$40,406,111,693',
  '$36,629,843,806',
  '$40,895,322,851'],
 ['Latvia',
  '$43,627,078,481',
  '$40,422,521,943',
  '$39,443,126,174',
  '$34,390,910,339',
  '$34,225,547,537'],
 ['Bahrain',
  '$43,205,000,000',
  '$44,383,297,872',
  '$39,288,670,213',
  '$34,621,807,713',
  '$38,653,318,085'],
 ['Paraguay',
  '$42,956,263,544',
  '$41,952,910,858',
  '$39,950,899,939',
  '$35,432,178,068',
  '$37,925,338,329'],
 ['Nepal',
  '$40,908,073,367',
  '$41,182,939,601',
  '$36,924,841,394',
  '$33,433,659,301',
  '$34,186,180,699'],
 ['Estonia',
  '$40,744,848,828',
  '$37,921,480,882',
  '$36,864,792,512',
  '$31,330,419,851',
  '$31,290,453,294'],
 ['Honduras',
  '$34,400,509,852',
  '$31,426,041,807',
  '$28,144,331,507',
  '$23,352,232,484',
  '$24,882,225,742'],
 ['El Salvador',
  '$34,015,620,000',
  '$31,988,920,000',
  '$29,043,140,000',
  '$24,921,190,000',
  '$26,881,140,000'],
 ['Cyprus',
  '$32,229,622,669',
  '$29,250,532,020',
  '$29,482,912,835',
  '$25,227,189,745',
  '$25,947,020,102'],
 ['Cambodia',
  '$31,772,759,999',
  '$29,504,829,319',
  '$26,961,061,152',
  '$25,872,797,892',
  '$27,089,390,033'],
 ['Iceland',
  '$31,020,032,583',
  '$28,701,830,402',
  '$25,797,870,984',
  '$21,629,953,194',
  '$24,681,343,649'],
 ['Senegal',
  '$31,013,986,429',
  '$27,619,479,060',
  '$27,520,784,130',
  '$24,530,513,038',
  '$23,403,995,992'],
 ['Papua New Guinea',
  '$30,932,496,250',
  '$31,603,619,037',
  '$26,113,333,240',
  '$23,848,445,104',
  '$24,751,066,911'],
 ['Georgia',
  '$30,535,530,479',
  '$24,984,568,960',
  '$18,853,115,589',
  '$16,010,869,216',
  '$17,638,337,117'],
 ['Zambia',
  '$28,162,630,954',
  '$29,163,782,140',
  '$22,096,416,932',
  '$18,137,764,931',
  '$23,308,667,781'],
 ['Trinidad And Tobago',
  '$28,139,944,790',
  '$30,053,575,132',
  '$24,496,505,941',
  '$20,807,571,314',
  '$23,775,754,305'],
 ['Bosnia',
  '$27,054,889,363',
  '$24,534,663,636',
  '$23,672,712,242',
  '$20,226,036,564',
  '$20,482,608,755'],
 ['Zimbabwe',
  '$26,538,273,499',
  '$27,366,627,153',
  '$28,371,238,666',
  '$21,509,698,406',
  '$21,832,234,926'],
 ['Armenia',
  '$24,212,134,631',
  '$19,513,474,648',
  '$13,878,908,629',
  '$12,641,698,583',
  '$13,619,290,539'],
 ['Guinea',
  '$23,612,295,818',
  '$20,999,229,260',
  '$16,091,817,842',
  '$14,177,835,841',
  '$13,442,861,496'],
 ['Albania',
  '$22,977,677,861',
  '$18,916,378,861',
  '$17,930,565,119',
  '$15,162,734,205',
  '$15,401,826,127'],
 ['Malta',
  '$20,956,999,452',
  '$18,357,069,273',
  '$18,123,718,947',
  '$15,249,999,048',
  '$16,004,563,886'],
 ['Mali',
  '$20,904,898,296',
  '$18,780,322,204',
  '$19,309,463,508',
  '$17,465,392,764',
  '$17,280,250,810'],
 ['Mozambique',
  '$20,624,597,847',
  '$18,406,835,495',
  '$16,168,055,475',
  '$14,235,420,174',
  '$15,512,758,965'],
 ['Gabon',
  '$20,516,134,389',
  '$21,071,739,228',
  '$20,217,946,921',
  '$15,314,577,168',
  '$16,874,405,460'],
 ['Burkina Faso',
  '$20,324,617,839',
  '$18,820,219,331',
  '$19,643,166,854',
  '$17,725,010,531',
  '$16,032,813,502'],
 ['Mongolia',
  '$19,872,180,370',
  '$17,146,471,714',
  '$15,286,441,738',
  '$13,312,981,429',
  '$14,206,359,018'],
 ['Haiti',
  '$19,850,829,758',
  '$20,253,551,921',
  '$20,877,414,953',
  '$14,508,222,518',
  '$15,016,090,930'],
 ['Benin',
  '$19,673,284,686',
  '$17,425,418,044',
  '$17,687,623,530',
  '$15,686,741,884',
  '$14,390,708,751'],
 ['Jamaica',
  '$19,423,355,367',
  '$17,097,760,687',
  '$14,657,586,159',
  '$13,812,421,836',
  '$15,830,766,531'],
 ['Botswana',
  '$19,395,765,126',
  '$20,321,958,850',
  '$18,750,946,600',
  '$14,960,291,106',
  '$16,725,908,149'],
 ['Nicaragua',
  '$17,829,215,284',
  '$15,649,934,215',
  '$14,144,067,556',
  '$12,681,548,304',
  '$12,699,046,245'],
 ['West Bank And Gaza',
  '$17,396,300,000',
  '$19,165,500,000',
  '$18,109,000,000',
  '$15,531,700,000',
  '$17,133,500,000'],
 ['Niger',
  '$16,819,170,421',
  '$15,433,852,712',
  '$14,915,002,436',
  '$13,744,653,103',
  '$12,889,555,561'],
 ['Guyana',
  '$16,786,302,158',
  '$14,718,388,489',
  '$8,041,362,110',
  '$5,471,256,595',
  '$5,173,760,192'],
 ['Moldova',
  '$16,539,436,547',
  '$14,510,490,660',
  '$13,691,869,264',
  '$11,530,746,234',
  '$11,736,797,055'],
 ['Madagascar',
  '$16,031,702,915',
  '$15,302,510,500',
  '$14,554,754,117',
  '$13,051,441,204',
  '$14,104,664,679'],
 ['Lao PDR',
  '$15,843,155,731',
  '$15,468,785,204',
  '$18,827,148,531',
  '$18,981,805,250',
  '$18,740,561,513'],
 ['Republic Of Congo',
  '$15,321,055,818',
  '$15,817,030,157',
  '$14,825,690,210',
  '$11,468,688,141',
  '$13,976,637,329'],
 ['Brunei',
  '$15,128,292,954',
  '$16,681,536,467',
  '$14,006,496,617',
  '$12,005,799,654',
  '$13,469,235,365'],
 ['North Macedonia',
  '$14,761,237,042',
  '$13,711,469,681',
  '$14,000,283,827',
  '$12,361,036,914',
  '$12,606,338,449'],
 ['Mauritius',
  '$14,397,127,281',
  '$12,927,979,286',
  '$11,484,348,766',
  '$11,408,106,446',
  '$14,436,346,980'],
 ['Bahamas',
  '$14,338,500,000',
  '$13,136,400,000',
  '$11,368,900,000',
  '$9,958,200,000',
  '$13,016,200,000'],
 ['Rwanda',
  '$14,097,768,648',
  '$13,316,160,804',
  '$11,069,280,277',
  '$10,174,387,614',
  '$10,349,299,856'],
 ['Malawi',
  '$14,084,341,062',
  '$13,129,458,326',
  '$12,580,922,008',
  '$12,041,250,084',
  '$11,077,305,330'],
 ['Kyrgyz Republic',
  '$13,987,627,909',
  '$12,134,931,018',
  '$9,249,133,946',
  '$8,270,468,614',
  '$9,371,275,264'],
 ['Chad',
  '$13,149,325,359',
  '$12,396,807,590',
  '$11,779,981,332',
  '$10,715,396,042',
  '$11,314,951,092'],
 ['Namibia',
  '$12,351,024,844',
  '$12,567,271,005',
  '$12,402,486,184',
  '$10,583,748,542',
  '$12,541,928,103'],
 ['Equatorial Guinea',
  '$12,116,922,539',
  '$13,486,788,879',
  '$12,215,878,033',
  '$9,893,816,008',
  '$11,364,133,550'],
 ['Tajikistan',
  '$12,060,602,009',
  '$10,713,525,200',
  '$8,937,805,347',
  '$8,133,963,551',
  '$8,300,813,599'],
 ['Somalia',
  '$11,679,800,110',
  '$10,419,541,202',
  '$9,838,711,529',
  '$9,204,140,383',
  '$9,420,431,258'],
 ['Mauritania',
  '$10,452,577,063',
  '$9,744,039,515',
  '$9,222,536,364',
  '$8,260,752,385',
  '$7,894,764,886'],
 ['Kosovo',
  '$10,438,351,483',
  '$9,354,903,062',
  '$9,413,403,724',
  '$7,717,145,218',
  '$7,899,737,577'],
 ['Togo',
  '$9,171,261,835',
  '$8,169,476,149',
  '$8,342,243,646',
  '$7,400,284,168',
  '$6,992,700,101'],
 ['Montenegro',
  '$7,404,541,965',
  '$6,229,801,581',
  '$5,861,427,505',
  '$4,769,996,866',
  '$5,542,054,181'],
 ['Maldives',
  '$6,600,000,000',
  '$6,170,638,746',
  '$5,254,366,312',
  '$3,712,604,583',
  '$5,726,094,799'],
 ['Barbados',
  '$6,393,564,190',
  '$5,840,673,700',
  '$4,945,276,000',
  '$4,779,756,550',
  '$5,367,139,250'],
 ['Fiji',
  '$5,494,797,541',
  '$4,979,979,531',
  '$4,305,031,650',
  '$4,432,466,220',
  '$5,444,407,198'],
 ['Eswatini',
  '$4,597,855,845',
  '$4,790,922,789',
  '$4,850,842,541',
  '$3,982,236,694',
  '$4,495,267,266'],
 ['Liberia',
  '$4,332,000,000',
  '$4,001,047,000',
  '$3,513,049,520',
  '$3,176,126,340',
  '$3,319,596,500'],
 ['Djibouti',
  '$4,098,530,514',
  '$3,674,298,479',
  '$3,385,825,229',
  '$3,185,150,981',
  '$3,088,853,639'],
 ['Sierra Leone',
  '$3,809,832,237',
  '$4,094,563,859',
  '$4,249,234,704',
  '$4,062,906,266',
  '$4,076,578,699'],
 ['Suriname',
  '$3,782,437,296',
  '$3,620,987,993',
  '$3,081,401,726',
  '$2,911,807,496',
  '$4,016,040,575'],
 ['Andorra',
  '$3,727,673,593',
  '$3,380,602,043',
  '$3,324,683,012',
  '$2,891,001,149',
  '$3,155,149,348'],
 ['Belize',
  '$3,281,500,000',
  '$2,830,507,576',
  '$2,424,575,179',
  '$2,047,727,810',
  '$2,386,792,476'],
 ['Burundi',
  '$2,642,161,669',
  '$3,338,722,828',
  '$2,775,798,697',
  '$2,649,680,261',
  '$2,576,518,880'],
 ['Cabo Verde',
  '$2,587,252,076',
  '$2,303,738,020',
  '$2,051,842,610',
  '$1,821,565,614',
  '$2,252,177,124'],
 ['Central African Republic',
  '$2,555,492,085',
  '$2,382,618,615',
  '$2,516,498,412',
  '$2,326,720,900',
  '$2,221,301,351'],
 ['St. Lucia',
  '$2,519,925,939',
  '$2,343,703,788',
  '$1,834,796,402',
  '$1,497,825,994',
  '$2,092,081,549'],
 ['Gambia',
  '$2,339,904,157',
  '$2,175,099,790',
  '$2,014,158,843',
  '$1,812,170,891',
  '$1,813,609,692'],
 ['Timor-Leste',
  '$2,243,142,908',
  '$3,204,753,000',
  '$3,621,958,000',
  '$2,162,619,200',
  '$2,027,034,000'],
 ['Seychelles',

In [140]:
#Combine Headers and Data into a DataFrame
web_df = pd.DataFrame(row_data, columns=headers)

web_df.head()

,Country Name,2023,2022,2021,2020,2019
0,United States,"$27,360,935,000,000","$25,744,108,000,000","$23,594,031,000,000","$21,322,950,000,000","$21,521,395,000,000"
1,China,"$17,794,781,986,105","$17,881,783,387,001","$17,820,459,508,852","$14,687,744,162,801","$14,279,968,506,272"
2,Germany,"$4,456,081,016,706","$4,082,469,490,798","$4,278,503,934,690","$3,887,727,161,914","$3,889,177,589,255"
3,Japan,"$4,212,945,159,781","$4,256,410,760,724","$5,034,620,784,585","$5,055,587,093,502","$5,117,993,853,017"
4,India,"$3,549,918,918,778","$3,353,470,496,886","$3,167,270,623,261","$2,674,851,578,587","$2,835,606,256,559"

In [142]:
# STEP 1: Missing Data

# Check if there are any missing values
print(web_df.isnull().values.any())

False

In [144]:
# STEP 2: Check Data Types

#Check the data type of entire DataFrame:
print(web_df.dtypes)

Country Name    object
2023            object
2022            object
2021            object
2020            object
2019            object
dtype: object

In [146]:
# STEP 3: Convert Data Types
# Since currency is being stored as an object, convert it to float for ability to analyze

cols_to_convert = web_df.columns[1:]  # The first column is "Country Name" and should remain unchanged

# First remove the commas and dollar sign from the column
web_df[cols_to_convert] = web_df[cols_to_convert].apply(lambda x: x.str.replace(",", "").str.replace("$", ""))

# Now convert the results to a float
web_df[cols_to_convert] = web_df[cols_to_convert].astype('float')

#Check the data type of entire DataFrame:
print(web_df.dtypes)

Country Name     object
2023            float64
2022            float64
2021            float64
2020            float64
2019            float64
dtype: object

In [148]:
# STEP 4: Convert Data Types
# Now convert the Country Name column to a string
web_df['Country Name'] = web_df['Country Name'].astype("string")

#Check the data type of entire DataFrame:
print(web_df.dtypes)

Country Name    string[python]
2023                   float64
2022                   float64
2021                   float64
2020                   float64
2019                   float64
dtype: object

In [150]:
#STEP 5: MELT
# To match the format of my other data sources, pivot from "wide" to "long" format

web_df_melted = web_df.melt(id_vars = ["Country Name"],
                            var_name = "Year",
                            value_name = "GDP")

# View results for US to see if it worked:
web_df_melted.loc[web_df_melted["Country Name"] == "United States"]

      Country Name  Year           GDP
0    United States  2023  2.736094e+13
209  United States  2022  2.574411e+13
418  United States  2021  2.359403e+13
627  United States  2020  2.132295e+13
836  United States  2019  2.152140e+13

In [152]:
#Check the data type of entire DataFrame:
print(web_df_melted.dtypes)

Country Name    string[python]
Year                    object
GDP                    float64
dtype: object

In [154]:
#STEP 6: Update data type again
# Now update datatype for Year from an object to int.
web_df_melted['Year'] = web_df_melted['Year'].astype("int")

print(web_df_melted.dtypes)

Country Name    string[python]
Year                     int32
GDP                    float64
dtype: object

In [156]:
# STEP 7: Find any duplicates
# Check for any duplicated values across all columns.
web_df_melted[web_df_melted.duplicated()]

Empty DataFrame
Columns: [Country Name, Year, GDP]
Index: []

In [158]:
# STEP 8: Handle $0 GDP Values
# There may be various reasons the data has $0 as a GDP value (Missing data, data errors, extremely small economies, extreme crises)
# However regardless of the reason, in reality, a country's GDP cannot exactly be $0.
# So in this step, we will convert $0 to NaN to prevent any misleading analysis.

# Find rows with GDP value of $0
zero = web_df_melted[web_df_melted["GDP"] ==0]
print(zero)

                 Country Name  Year  GDP
184            American Samoa  2023  0.0
185                     Aruba  2023  0.0
186             Faroe Islands  2023  0.0
187                   Lebanon  2023  0.0
188             New Caledonia  2023  0.0
189  St. Martin (French Part)  2023  0.0
190          French Polynesia  2023  0.0
191                     Tonga  2023  0.0
192               Afghanistan  2023  0.0
193                      Cuba  2023  0.0
194               Isle Of Man  2023  0.0
195                     Qatar  2023  0.0
196           Channel Islands  2023  0.0
197                San Marino  2023  0.0
198                   Curacao  2023  0.0
199                 Greenland  2023  0.0
200                    Monaco  2023  0.0
201                   Bermuda  2023  0.0
202            Cayman Islands  2023  0.0
203      Syrian Arab Republic  2023  0.0
204  Northern Mariana Islands  2023  0.0
205             Liechtenstein  2023  0.0
206     Virgin Islands (U.S.)  2023  0.0
207                      Guam  2023  0.0
208                    Bhutan  2023  0.0
398  St. Martin (French Part)  2022  0.0
402                      Cuba  2022  0.0
403               Isle Of Man  2022  0.0
406                San Marino  2022  0.0
408                 Greenland  2022  0.0
412      Syrian Arab Republic  2022  0.0
413  Northern Mariana Islands  2022  0.0
415     Virgin Islands (U.S.)  2022  0.0
611                      Cuba  2021  0.0
622  Northern Mariana Islands  2021  0.0
816  St. Martin (French Part)  2020  0.0

In [160]:
#Replace the 0 values with NaN
import numpy as np
web_df_melted["GDP"] = web_df_melted["GDP"].replace(0, np.nan)

# Check for 0s again
zero = web_df_melted[web_df_melted["GDP"] ==0]
print(zero)

Empty DataFrame
Columns: [Country Name, Year, GDP]
Index: []

In [124]:
# Print the final dataset

print("Final dataset:")
print(web_df_melted)

Final dataset:
                  Country Name  Year           GDP
0                United States  2023  2.736094e+13
1                        China  2023  1.779478e+13
2                      Germany  2023  4.456081e+12
3                        Japan  2023  4.212945e+12
4                        India  2023  3.549919e+12
...                        ...   ...           ...
1040  Northern Mariana Islands  2019  1.181000e+09
1041             Liechtenstein  2019  6.436467e+09
1042     Virgin Islands (U.S.)  2019  4.121000e+09
1043                      Guam  2019  6.355000e+09
1044                    Bhutan  2019  2.735683e+09

[1045 rows x 3 columns]

In [162]:
web_df_melted[web_df_melted['Country Name'] == 'United States']

      Country Name  Year           GDP
0    United States  2023  2.736094e+13
209  United States  2022  2.574411e+13
418  United States  2021  2.359403e+13
627  United States  2020  2.132295e+13
836  United States  2019  2.152140e+13

In [86]:
country_data_df = web_df_melted['Country Name']

In [88]:
country_data_df.to_csv('country_data.csv', index=False)

# Ethical Implications  

In the data transformation and cleaning process applied to the MacroTrends GDP website data, several steps were taken to enhance the dataset's usability and accuracy. First, the data was extracted from an online table, and currency formatting was removed to convert the GDP values into a numeric format. This was done so that, in future steps, numerical analysis could be conducted on these values. Additionally, the dataset was reformatted from a wide format to a long format to align with a future step in which we will join this data with that from Milestone 2, which follows the same format. Finally, another significant step taken was to replace any GDP values represented as `$0` with NaN in an effort to eliminate misleading analysis. This was an assumption taken during this phase of the project that should be thoroughly documented (as demonstrated in the code above). Treating `$0` GDP values as missing data, which, if incorrect, could impact any downstream analyses.
Unfortunately, one ethical concern arose regarding data ownership and programmatic access upon reviewing the site's terms of service. MacroTrends discourages automated extraction of data, which raises legal concerns. To mitigate this ethical risk, alternative open-data sources should be considered in the future, especially if the data is used beyond a school project, to ensure compliance with data access policies.
As for the credibility of this data source, the MacroTrends website sources its data directly from The World Bank, which is a highly credible and authoritative source for GDP data. The World Bank ensures high-quality data by using methodologies that are internationally accepted and encourages countries to improve the quality of their official statistics. However, it is important to note that there may be a lag in the availability of recent data due to the time required for data collection and validation from various countries. I believe this is evident in the `$0` GDP values, discussed earlier. For the most up-to-date data, official national websites may be a valuable resource to explore.

In [126]:
# ADDING CODE TO LOAD MILESTONE 3 (Website) DF INTO SQLite

import sqlite3
import pandas as pd

# Connect to (or create) the SQLite database
conn = sqlite3.connect("combined_data.db")  # Ensure all notebooks use the same filename

# Write the DataFrame to a table in SQLite
web_df_melted.to_sql("gdp_web", conn, if_exists="replace", index=False)

# Close the connection
conn.close()